ifndef SWE_DISABLE_AUDIO
#LIBS := $(LIBS) -lSDL -lmad -lvorbisfile -lvorbis -logg
endif

ifndef WITHOUT_UNICODE
LIBS	:= $(LIBS) -lfreetype
endif

IDICON	:= 1099
RESICON := SWE_lua.res
AR	:= arm-mingw32ce-ar
CXX	:= arm-mingw32ce-g++
WINDRES	:= arm-mingw32ce-windres
STRIP	:= arm-mingw32ce-strip
EXT	:= _wince.exe
CFLAGS	:= $(CFLAGS) -DSWE_SDL12 -DWINCE -static
LIBS	:= -Wl,-Bstatic $(LIBS) -lmmtimer
LDFLAGS	:= -static $(LDFLAGS) -Wl,--gc-sections
